name: Action to extract delimited unique matches from a string
description: All unique matches in comma separated format or an empty string

inputs:
  regex:
    required: true
    description: The regex to match
  input:
    required: true
    description: The string to match against
  flags:
    required: false
    description: The flags to use for the regex
    default: gi

outputs:
  matches:
    description: All unique matches in comma separated format

runs:
  using: node16
  main: index.js

branding:
  icon: search
  color: yellow
