on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Match Regex All
        id: match
        uses: ./
        with:
          regex: '[a-z0-9._-]+@[a-z0-9._-]+\.[a-z0-9_-]+'
          input: a@foo.baz\n b.a@aa.io\n b.a@aa.io
          flags: gi
          delimiter: '|'
      - run: |
          echo "Matched: ${{ steps.match.outputs.matches }}"

